export const SET_USER = "SET_USER";
export const SET_PRODUCT = "SET_PRODUCT";
export const SET_CONFIRMED_PRODUCT = "SET_CONFIRMED_PRODUCT";
export const SET_PRODUCT_FOR_EDITING = "SET_PRODUCT_FOR_EDITING";
export const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
